### ISSUE TITLE
Failing tests and errors

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#81]
Hi, here a report of what I'm seeing at the moment, on Linux, QGIS 2.14.7. Both the Tester and GeoGig plugin updated to the latest version available in the dev repo. The tests have been run in two separate setups, with GeoGig server running locally, and with GeoGig server running in the new Docker container. In this second case in the "docker run" command has been added the flag to mount locally ("/home/gioivanni/geogig/server") the folder in the container ("/geogig_repo") that is being published by GeoGig server (see: https://github.com/elpaso/docker-geogig/blob/master/setup.sh). Commands issues:

docker pull boundlessgeodesktop/geogig:1.0-RC3

docker run -e USER='Giovanni Manghi' -e EMAIL_ADDRESS='giovanni.mangh@boundlessgeo.com' --name="geogig" -p 8182:8182 -v /home/giovanni/geogig/server:/geogig_repo -d boundlessgeodesktop/geogig:1.0-RC3

Reports saved from within the Tester plugin attached.

[linux.zip](https://github.com/boundlessgeo/qgis-geogiglight-plugin/files/510598/linux.zip)

Please note that when running the tests using GeoGig in the container:

a (python?) error also is shown in QGIS message bar, no stack trace (see attached image).
![screenshot_20161005_085409](https://cloud.githubusercontent.com/assets/1951107/19107781/c4847b6a-8ae5-11e6-88e8-969f2e67d0b4.png)

**Comment by gioman** [comment]
Note: I previously added by mistake this report in the Tester plugin tracker. One of the attached reports from the Tester plugin was also wrong, the right one is attached here.

**Comment by gioman** [comment]
Results on macOS here attached, same setups as for Linux, this time using the latest build available for macOS of Boundless Desktop.

[os_x.zip](https://github.com/boundlessgeo/qgis-geogiglight-plugin/files/510943/os_x.zip)

On macOS two errors show in message bar (both when using GeoGig locally or in the Docker container):

<img width="1280" alt="screen shot 2016-10-05 at 10 37 38" src="https://cloud.githubusercontent.com/assets/1951107/19110791/f8a5134c-8af3-11e6-9f21-1d6aeba498cc.png">

<img width="1280" alt="screen shot 2016-10-05 at 10 37 47" src="https://cloud.githubusercontent.com/assets/1951107/19110802/0085df1a-8af4-11e6-89c5-29a36470aa9d.png">

**Comment by gioman** [comment]
On macOS some results in the real testing setup: Tester plugin run inside the testing VM for BL Desktop, GeoGig server un in the container in the host.

**Comment by volaya** [comment]
Tests ares fixed now except for the testConflictsXXXX ones.

They pass in my machine, but, looking at the error traces, it seems that in your environment, the layers are not being correctly modified before doing the import (probably due to issues with geopackage...). That would explain those messages that you get...

I have added an extra check, so before commiting the change that will cause the conflict, it verifies that the layer has the conflicting change. Could you re-run those tests and send me the resulting failure report?

**Comment by gioman** [comment]
Hi Victor, I updated the Tester and GeoGig plugins, and here following the results on macOS and Windows (using the tests VMs and the GeoGig docker container)

[geogig_tests_gg_container061016_osx.html.zip](https://github.com/boundlessgeo/qgis-geogiglight-plugin/files/513488/geogig_tests_gg_container061016_osx.html.zip)

**Comment by gioman** [comment]
Windows:

[geogig_tests_gg_container061016_windows.html.zip](https://github.com/boundlessgeo/qgis-geogiglight-plugin/files/513490/geogig_tests_gg_container061016_windows.html.zip)

**Comment by gioman** [comment]
Just a note: I have seen all green running the tests on a QGIS master installation on Linux. If on the smae machine I try on 2.14.3 (gdal 2.1) I still see the same tests as above fail.

**Comment by gioman** [comment]
@volaya this can be related to the new issue with the gpkg: using a qgis version without the first gpkg fix is all green.

**Comment by gioman** [comment]
@volaya with the latest code revision and GG server RC3 (the one in latest Docker container for testing) and BL Desktop 1.0.0 final, all the automated test are now passing.
